# Configuration for baseline IPHR evaluation

# Number of questions to evaluate
num_samples: 20

# Batch size for inference (adjust based on GPU memory)
batch_size: 4

# Maximum number of question files to load from
max_files: 10

# Maximum examples to store per category for report
max_examples_per_category: 3

# Categories to sample from (excluding book page counts)
diverse_categories:
  - aircraft-speeds
  - animals-speed
  - boiling-points
  - bridge-lengths
  - celebrity-heights
  - element-densities
  - mountain-heights
  - river-lengths
  - skyscraper-heights
  - train-speeds
  - wm-movie-release
  - wm-person-age
  - wm-us-city-popu
  - structure-completion
  - tech-releases
  - melting-points
  - satellite-launches
  - wm-person-birth
  - wm-song-release
  - element-numbers

# Model configuration
model_name: "Qwen/Qwen2.5-7B-Instruct"
device: "cuda:0"
dtype: "bfloat16"

# Generation parameters
max_new_tokens: 300
temperature: 0.7
do_sample: true